In [3]:
a = "hello"
print(type(a))
print(dir(a)) #return all methods and attribute

<class 'str'>
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

All **methods**/function, **Attributes**/propeties/feilds
* method_name()
* 'attribute_name'
* How to call  method or attributs
        * 'object_name.method_name()
        * 'object_name.attribute_name'

In [8]:
text = """Pakistan zIndada bAd!
we Love our cOuntry."""

print(text.capitalize()) #capitalize first letter of word
#use tab after dot - shwow available method

Pakistan zindada bad!
we love our country.

In [9]:
text = """Pakistan zIndada bAd!
we Love our cOuntry."""

print(text.casefold()) #ignor Capital from string

pakistan zindada bad!
we love our country.

In [12]:
name = "Roshana"

print(len(name)) #ignor Capital from string len is global method
print(name.__len__()) # __len__ name method

7
7

In [13]:
name = "Roshana"

name.center(20) #center the text
#shift + tab show methods
#jupyter noteboo return last as output

'      Roshana       '

In [17]:
name = "I love my country "
print(name.count('o')) #return count of o
print(name.count('my')) #return count of o
#count method alwyas return integer

2
0

In [22]:
name = "I love my country "
name = name.casefold()
print("y count:",name.count('y'),"m count :",name.count('m'))

y count: 2 m count : 1

In [1]:
#encode - ASCI CODE -> UTF-8
#https://www.w3schools.com/python/ref_string_encode.asp
txt = "Hello GÃ¼nter"
print(txt.encode(encoding="ascii",errors="backslashreplace"))
print(txt.encode(encoding="ascii",errors="ignore"))
print(txt.encode(encoding="ascii",errors="namereplace"))
print(txt.encode(encoding="ascii",errors="replace"))
print(txt.encode(encoding="ascii",errors="xmlcharrefreplace"))

#x = txt.decode()
#print(x)

b'Hello G\\xfcnter'
b'Hello Gnter'
b'Hello G\\N{LATIN SMALL LETTER U WITH DIAERESIS}nter'
b'Hello G?nter'
b'Hello G&#252;nter'

In [32]:
txt = "Hello"

print(txt.startswith('H'))
print(txt.endswith('o'))

True
True

In [40]:
card = """
Ned University
Batch 5
Class:\tPython
Name:\tRoshana
"""
print(card.expandtabs(20))#give tabs -tabs start from first letter

Ned University
Batch 5
Class:              Python
Name:               Roshana

**Help**
* help(function)
* help(obj.method)
* function?
* ?function
* ??function
* function(shift + tab)

In [48]:
print??

In [46]:
name  = "HeLLo woLd"
?name.lower()

Object `name.lower()` not found.

In [51]:
name = "    Rosh    "
name.lstrip()
name.rstrip()

'    Rosh'

In [52]:
name = "    Rosh    "
name.rstrip()

'    Rosh'

In [53]:
name = "    Rosh    "
name.strip()

'Rosh'

In [54]:
name = "Rosh"
name.replace("Rosh","Roshana")

'Roshana'

In [59]:
name = "Rosh Rosh"
name.replace("Rosh","Mughal",1)

'Mughal Rosh'

In [68]:
name = "this is Pakistan"
name.index("Pakistan")

8

In [64]:
name = "this is Pakistan"
name.find("this",6)

-1

In [67]:
name = "this is Pakistan"
name.count("Pakistan")

1

In [67]:
# Additonal Task - Regex


* txt = re.findall('regex',data)#fatch required pattend data// \d{13}

* df = pd.DataFrame({"CNIC":txt}) # give format

* d = pd.DataFrame(txt,columns=["Time","Name","Rol; No"]) #multiple columns

* df.to_excel("attendance.xlsx", index = False) #skip index - export in excel

*!pip install openpyxl # install missing dependancy

SyntaxError: invalid syntax (3514028382.py, line 12)

#### text = """
Iqra Ismail1:01â¯PM
no
Feroz Gul2:26â¯PM
44204-3335269-3
Jawwad Khan2:26â¯PM
42201-9848624-7
Mahnoor Shoukat2:26â¯PM
4250150754028
hanfia sattar2:26â¯PM
4220151056096
Hiba Rafiq2:26â¯PM
4230185868058
Sadia Javed2:26â¯PM
4220158772002
Hafsa Imtiaz2:26â¯PM
42201-8903447-4
Fahad Hashmi2:27â¯PM
4210180636569
Iqra Ismail2:27â¯PM
4220113160602
Azeem Khan2:27â¯PM
42101-7583355-9
muhammad usman2:27â¯PM
33203-1390549-7
Owais Saeed2:27â¯PM
4210187416487
Dareer Khalid2:27â¯PM
4220103150553
Tauqir Ahmed2:27â¯PM
4220157915361
asad ahmad2:27â¯PM
3130349769793
FJ2:27â¯PM
4210174737043
Abdul Rehman2:27â¯PM
4210113955917
Danish Siddiquie2:27â¯PM
4230174890321
Huzaifa Aazmi2:27â¯PM
42101-4717980-5
Waqas Khan2:27â¯PM
35202-2018037-1
Memon Nadeemhabib2:27â¯PM
4130627627273
Habib Sufyan2:27â¯PM
42101-9546976-1
waqar saleem2:27â¯PM
3740611871985
Muhammad Umer Farooq2:27â¯PM
4250141745875
Ali Mehdi2:27â¯PM
42101-0883203-9
Taj Ahmed2:27â¯PM
42101-5086613-3
Siyam Ansari2:27â¯PM
45504-6691184-5
Asfa Tabish2:27â¯PM
42201-3317436-4
Gul Zaman Shaikh2:27â¯PM
42301-4208474-9
Gul Zaman
Rohan Wasim2:27â¯PM
4210156852483
Mahek Ali2:27â¯PM
4220119350184
Irtiqa Khan2:27â¯PM
42501-1882684-3
Hammad Khan2:27â¯PM
42201-2206678-9
mansoor ahmed2:27â¯PM
41303-1217008-9
imran jamil2:27â¯PM
42201-2367694-3
Junaid Khan2:27â¯PM
4250118835393
Saira Shaikh2:27â¯PM
4220182635186
Shariq Bashir2:27â¯PM
42101-1743803-7
Asmat Mehmood2:27â¯PM
423018695739
Raheel Nadeem2:27â¯PM
4220114028509
Saba Ali2:27â¯PM
42301-3905834-2
You2:27â¯PM
4420654603848
adeel Zaman2:27â¯PM
4240116015521 adeel zaman
Ashar Khaliq2:27â¯PM
4200004676915
syed farman ali shah2:27â¯PM
1510203461495
Haroon Saleem2:27â¯PM
4240156992579
Shakeel Ahmed2:27â¯PM
4240119589433
Syed Usman Ghani2:27â¯PM
4210109155877
Abdul Samad Shaikh2:27â¯PM
4210255467543
Muhammad Saad2:27â¯PM
42201-4144981-5
Vishah Fatima2:27â¯PM
4210170628928
KAMRAN KHATRI2:27â¯PM
4230198076489
Shafaat Ahmed Khan2:27â¯PM
42201-3225780-3
Uzma Farogh2:27â¯PM
4210190028920
Akbar Khan2:27â¯PM
4220106865377
bilal2:28â¯PM
4210164911883
Bilal Khan2:28â¯PM
42501-3607843-1
Abdul Samad Shaikh2:28â¯PM
4210184328497
Xyz2:28â¯PM
4210118094301
Mahpara Badar2:28â¯PM
4210111752498
Hasan Mehdi2:28â¯PM
4210144676677
Imran Khan2:28â¯PM
4130498094753
Jahanzeb Siddiqui2:29â¯PM
4210169925379
Omema Akhtar2:29â¯PM
4210151840638 omema Akhtar
Raniya Khan2:29â¯PM
42201-9978093-2
aqsa akmal2:29â¯PM
4220145184200
Javeed Ahmed2:30â¯PM
4220141864935
Ashar Khaliq2:30â¯PM
%d
faranaz keshwani2:31â¯PM
42201-7992036-2
42201-7992036-2 Faranaz Surani
Ahmed Naseem2:32â¯PM
13 digit
Saba Ali2:32â¯PM
13
Talaal Yousoof2:32â¯PM
13
Danish Siddiquie2:32â¯PM
13
oua-hnxh-hzq
"""
import re
cnic = re.findall('\d+',text) #look for numbers
print(cnic)

In [68]:
text = text = """
Team NED Academy12:59â¯PM
Sir please start recording  pleas
Iqra Ismail1:01â¯PM
no
Muhammad Abubakar1:01â¯PM
sir class end pe assignment ke baray mei thora guide krdejye ga
Iqra Ismail1:02â¯PM
yes
Altaf Hussain Bakhwani1:04â¯PM
yes
Muhammad Abubakar1:04â¯PM
clear hai sir
Talaal Yousoof1:04â¯PM
yes
Altaf Hussain Bakhwani1:07â¯PM
yes, action = method, character = attribute
Talaal Yousoof1:09â¯PM
what was attribute pls?
Uzma Farogh1:09â¯PM
sir some students are trying to join. please let them in
faranaz keshwani1:12â¯PM
how do you record attendance on online classes
Asfa Tabish1:23â¯PM
sir method and attribute repeat krdain pls
Ahmed Naseem1:25â¯PM
Yes, main ne bhi late join kiya hai. It would be helpful if you can revise a bit.
Ashar Khaliq1:39â¯PM
print(name.lower().count("m"))
Rosh Mirza1:41â¯PM
name = "I love my country "
name = name.casefold()
print("y count:",name.count('y'),"m count :",name.count('m'))
You2:17â¯PM
24mrw4t
Imran Haider2:26â¯PM
3130315904511
Muhammad Abubakar2:26â¯PM
42201-1270634-5
Aamir Pingal2:26â¯PM
423012945634
Talaal Yousoof2:26â¯PM
4220158211299
Ahmed Naseem2:26â¯PM
4200066399757
Muhammad Ovais2:26â¯PM
42101-4941-769-5
Atif Salam2:26â¯PM
42201-9446591-3
Altaf Hussain Bakhwani2:26â¯PM
4220105815527
Feroz Gul2:26â¯PM
44204-3335269-3
Jawwad Khan2:26â¯PM
42201-9848624-7
Mahnoor Shoukat2:26â¯PM
4250150754028
hanfia sattar2:26â¯PM
4220151056096
Hiba Rafiq2:26â¯PM
4230185868058
Sadia Javed2:26â¯PM
4220158772002
Hafsa Imtiaz2:26â¯PM
42201-8903447-4
Fahad Hashmi2:27â¯PM
4210180636569
Iqra Ismail2:27â¯PM
4220113160602
Azeem Khan2:27â¯PM
42101-7583355-9
muhammad usman2:27â¯PM
33203-1390549-7
Owais Saeed2:27â¯PM
4210187416487
Dareer Khalid2:27â¯PM
4220103150553
Tauqir Ahmed2:27â¯PM
4220157915361
asad ahmad2:27â¯PM
3130349769793
FJ2:27â¯PM
4210174737043
Abdul Rehman2:27â¯PM
4210113955917
Danish Siddiquie2:27â¯PM
4230174890321
Huzaifa Aazmi2:27â¯PM
42101-4717980-5
Waqas Khan2:27â¯PM
35202-2018037-1
Memon Nadeemhabib2:27â¯PM
4130627627273
Habib Sufyan2:27â¯PM
42101-9546976-1
waqar saleem2:27â¯PM
3740611871985
Muhammad Umer Farooq2:27â¯PM
4250141745875
Ali Mehdi2:27â¯PM
42101-0883203-9
Taj Ahmed2:27â¯PM
42101-5086613-3
Siyam Ansari2:27â¯PM
45504-6691184-5
Asfa Tabish2:27â¯PM
42201-3317436-4
Gul Zaman Shaikh2:27â¯PM
42301-4208474-9
Gul Zaman
Rohan Wasim2:27â¯PM
4210156852483
Mahek Ali2:27â¯PM
4220119350184
Irtiqa Khan2:27â¯PM
42501-1882684-3
Hammad Khan2:27â¯PM
42201-2206678-9
mansoor ahmed2:27â¯PM
41303-1217008-9
imran jamil2:27â¯PM
42201-2367694-3
Junaid Khan2:27â¯PM
4250118835393
Saira Shaikh2:27â¯PM
4220182635186
Shariq Bashir2:27â¯PM
42101-1743803-7
Asmat Mehmood2:27â¯PM
423018695739
Raheel Nadeem2:27â¯PM
4220114028509
Saba Ali2:27â¯PM
42301-3905834-2
adeel Zaman2:27â¯PM
4240116015521 adeel zaman
Rosh Mirza2:27â¯PM
4420654603848
Ashar Khaliq2:27â¯PM
4200004676915
syed farman ali shah2:27â¯PM
1510203461495
Haroon Saleem2:27â¯PM
4240156992579
Shakeel Ahmed2:27â¯PM
4240119589433
Syed Usman Ghani2:27â¯PM
4210109155877
Abdul Samad Shaikh2:27â¯PM
4210255467543
Muhammad Saad2:27â¯PM
42201-4144981-5
Vishah Fatima2:27â¯PM
4210170628928
KAMRAN KHATRI2:27â¯PM
4230198076489
Shafaat Ahmed Khan2:27â¯PM
42201-3225780-3
Uzma Farogh2:27â¯PM
4210190028920
Akbar Khan2:27â¯PM
4220106865377
bilal2:28â¯PM
4210164911883
4210164911883
Bilal Khan2:28â¯PM
42501-3607843-1
Abdul Samad Shaikh2:28â¯PM
4210184328497
Xyz2:28â¯PM
4210118094301
Mahpara Badar2:28â¯PM
4210111752498
Hasan Mehdi2:28â¯PM
4210144676677
Imran Khan2:28â¯PM
4130498094753
Jahanzeb Siddiqui2:29â¯PM
4210169925379
Omema Akhtar2:29â¯PM
4210151840638 omema Akhtar
Raniya Khan2:29â¯PM
42201-9978093-2
aqsa akmal2:29â¯PM
4220145184200
Javeed Ahmed2:30â¯PM
4220141864935
Ashar Khaliq2:30â¯PM
%d
faranaz keshwani2:31â¯PM
42201-7992036-2
42201-7992036-2 Faranaz Surani
Ahmed Naseem2:32â¯PM
13 digit
Saba Ali2:32â¯PM
13
Talaal Yousoof2:32â¯PM
13
Danish Siddiquie2:32â¯PM
13
"""
#import 
import re
cnic = re.findall('\d{13}',text) #look for 13 digit numbers
print(cnic)

['3130315904511', '4220158211299', '4200066399757', '4220105815527', '4250150754028', '4220151056096', '4230185868058', '4220158772002', '4210180636569', '4220113160602', '4210187416487', '4220103150553', '4220157915361', '3130349769793', '4210174737043', '4210113955917', '4230174890321', '4130627627273', '3740611871985', '4250141745875', '4210156852483', '4220119350184', '4250118835393', '4220182635186', '4220114028509', '4240116015521', '4420654603848', '4200004676915', '1510203461495', '4240156992579', '4240119589433', '4210109155877', '4210255467543', '4210170628928', '4230198076489', '4210190028920', '4220106865377', '4210164911883', '4210164911883', '4210184328497', '4210118094301', '4210111752498', '4210144676677', '4130498094753', '4210169925379', '4210151840638', '4220145184200', '4220141864935']

In [69]:
data = """
Iqra Ismail1:01â¯PM
no
Feroz Gul2:26â¯PM
44204-3335269-3
Jawwad Khan2:26â¯PM
42201-9848624-7
Mahnoor Shoukat2:26â¯PM
4250150754028
hanfia sattar2:26â¯PM
4220151056096
Hiba Rafiq2:26â¯PM
4230185868058
Sadia Javed2:26â¯PM
4220158772002
Hafsa Imtiaz2:26â¯PM
42201-8903447-4
Fahad Hashmi2:27â¯PM
4210180636569
Iqra Ismail2:27â¯PM
4220113160602
Azeem Khan2:27â¯PM
42101-7583355-9
muhammad usman2:27â¯PM
33203-1390549-7
Owais Saeed2:27â¯PM
4210187416487
Dareer Khalid2:27â¯PM
4220103150553
Tauqir Ahmed2:27â¯PM
4220157915361
asad ahmad2:27â¯PM
3130349769793
FJ2:27â¯PM
4210174737043
Abdul Rehman2:27â¯PM
4210113955917
Danish Siddiquie2:27â¯PM
4230174890321
Huzaifa Aazmi2:27â¯PM
42101-4717980-5
Waqas Khan2:27â¯PM
35202-2018037-1
Memon Nadeemhabib2:27â¯PM
4130627627273
Habib Sufyan2:27â¯PM
42101-9546976-1
waqar saleem2:27â¯PM
3740611871985
Muhammad Umer Farooq2:27â¯PM
4250141745875
Ali Mehdi2:27â¯PM
42101-0883203-9
Taj Ahmed2:27â¯PM
42101-5086613-3
Siyam Ansari2:27â¯PM
45504-6691184-5
Asfa Tabish2:27â¯PM
42201-3317436-4
Gul Zaman Shaikh2:27â¯PM
42301-4208474-9
Gul Zaman
Rohan Wasim2:27â¯PM
4210156852483
Mahek Ali2:27â¯PM
4220119350184
Irtiqa Khan2:27â¯PM
42501-1882684-3
Hammad Khan2:27â¯PM
42201-2206678-9
mansoor ahmed2:27â¯PM
41303-1217008-9
imran jamil2:27â¯PM
42201-2367694-3
Junaid Khan2:27â¯PM
4250118835393
Saira Shaikh2:27â¯PM
4220182635186
Shariq Bashir2:27â¯PM
42101-1743803-7
Asmat Mehmood2:27â¯PM
423018695739
Raheel Nadeem2:27â¯PM
4220114028509
Saba Ali2:27â¯PM
42301-3905834-2
You2:27â¯PM
4420651643848
adeel Zaman2:27â¯PM
4240116015521 adeel zaman
Ashar Khaliq2:27â¯PM
4200004676915
syed farman ali shah2:27â¯PM
1510203461495
Haroon Saleem2:27â¯PM
4240156992579
Shakeel Ahmed2:27â¯PM
4240119589433
Syed Usman Ghani2:27â¯PM
4210109155877
Abdul Samad Shaikh2:27â¯PM
4210255467543
Muhammad Saad2:27â¯PM
42201-4144981-5
Vishah Fatima2:27â¯PM
4210170628928
KAMRAN KHATRI2:27â¯PM
4230198076489
Shafaat Ahmed Khan2:27â¯PM
42201-3225780-3
Uzma Farogh2:27â¯PM
4210190028920
Akbar Khan2:27â¯PM
4220106865377
bilal2:28â¯PM
4210164911883
Bilal Khan2:28â¯PM
42501-3607843-1
Abdul Samad Shaikh2:28â¯PM
4210184328497
Xyz2:28â¯PM
4210118094301
Mahpara Badar2:28â¯PM
4210111752498
Hasan Mehdi2:28â¯PM
4210144676677
Imran Khan2:28â¯PM
4130498094753
Jahanzeb Siddiqui2:29â¯PM
4210-16992537-9
Omema Akhtar2:29â¯PM
4210151840638 omema Akhtar
Raniya Khan2:29â¯PM
42201-9978093-2
aqsa akmal2:29â¯PM
4220145184200
Javeed Ahmed2:30â¯PM
4220141864935
Ashar Khaliq2:30â¯PM
%d
faranaz keshwani2:31â¯PM
42201-7992036-2
42201-7992036-2 Faranaz Surani
Ahmed Naseem2:32â¯PM
13 digit
Saba Ali2:32â¯PM
13
Talaal Yousoof2:32â¯PM
13
Danish Siddiquie2:32â¯PM
13
oua-hnxh-hzq
"""

import pandas as pd
import re


#text = textreplace("_","")
#name = re.findall('.+\d{1,2}:d{}',text) #name  r'\w'  // dot individual charctor
#dot pluse(.+) - complete string as word or line -except \n new line
#Rosh Mirza1:41â¯PM
#(Rosh Mirza)\d:\dâ¯PM)2:31â¯PM
#(.*)2:31â¯PM)2:31â¯PM
#\d = string
#? - optional

# = re.findall('.+\d{1,2}:d{}',data)
#d = re.findall('(.*?)(\d{2}:\d{2})â¯PM}',data)
d = re.findall('(.*)(\d{1,2}:\d{2})â¯PM',data)
#print(cnic)
d = pd.DataFrame(d,columns=["Name","Time"])
d

                Name  Time
0        Iqra Ismail  1:01
1          Feroz Gul  2:26
2        Jawwad Khan  2:26
3    Mahnoor Shoukat  2:26
4      hanfia sattar  2:26
..               ...   ...
69  faranaz keshwani  2:31
70      Ahmed Naseem  2:32
71          Saba Ali  2:32
72    Talaal Yousoof  2:32
73  Danish Siddiquie  2:32

[74 rows x 2 columns]

**Extract CNIC**

In [65]:
data = """
Team NED Academy12:59â¯PM
Sir please start recording  pleas
Iqra Ismail1:01â¯PM
no
Muhammad Abubakar1:01â¯PM
sir class end pe assignment ke baray mei thora guide krdejye ga
Iqra Ismail1:02â¯PM
yes
Altaf Hussain Bakhwani1:04â¯PM
yes
Muhammad Abubakar1:04â¯PM
clear hai sir
Talaal Yousoof1:04â¯PM
yes
Altaf Hussain Bakhwani1:07â¯PM
yes, action = method, character = attribute
Talaal Yousoof1:09â¯PM
what was attribute pls?
Uzma Farogh1:09â¯PM
sir some students are trying to join. please let them in
faranaz keshwani1:12â¯PM
how do you record attendance on online classes
Asfa Tabish1:23â¯PM
sir method and attribute repeat krdain pls
Ahmed Naseem1:25â¯PM
Yes, main ne bhi late join kiya hai. It would be helpful if you can revise a bit.
Ashar Khaliq1:39â¯PM
print(name.lower().count("m"))
Rosh Mirza1:41â¯PM
name = "I love my country "
name = name.casefold()
print("y count:",name.count('y'),"m count :",name.count('m'))
You2:17â¯PM
24mrw4t
Imran Haider2:26â¯PM
3130315904511
Muhammad Abubakar2:26â¯PM
42201-1270634-5
Aamir Pingal2:26â¯PM
423012945634
Talaal Yousoof2:26â¯PM
4220158211299
Ahmed Naseem2:26â¯PM
4200066399757
Muhammad Ovais2:26â¯PM
42101-4941-769-5
Atif Salam2:26â¯PM
42201-9446591-3
Altaf Hussain Bakhwani2:26â¯PM
4220105815527
Feroz Gul2:26â¯PM
44204-3335269-3
Jawwad Khan2:26â¯PM
42201-9848624-7
Mahnoor Shoukat2:26â¯PM
4250150754028
hanfia sattar2:26â¯PM
4220151056096
Hiba Rafiq2:26â¯PM
4230185868058
Sadia Javed2:26â¯PM
4220158772002
Hafsa Imtiaz2:26â¯PM
42201-8903447-4
Fahad Hashmi2:27â¯PM
4210180636569
Iqra Ismail2:27â¯PM
4220113160602
Azeem Khan2:27â¯PM
42101-7583355-9
muhammad usman2:27â¯PM
33203-1390549-7
Owais Saeed2:27â¯PM
4210187416487
Dareer Khalid2:27â¯PM
4220103150553
Tauqir Ahmed2:27â¯PM
4220157915361
asad ahmad2:27â¯PM
3130349769793
FJ2:27â¯PM
4210174737043
Abdul Rehman2:27â¯PM
4210113955917
Danish Siddiquie2:27â¯PM
4230174890321
Huzaifa Aazmi2:27â¯PM
42101-4717980-5
Waqas Khan2:27â¯PM
35202-2018037-1
Memon Nadeemhabib2:27â¯PM
4130627627273
Habib Sufyan2:27â¯PM
42101-9546976-1
waqar saleem2:27â¯PM
3740611871985
Muhammad Umer Farooq2:27â¯PM
4250141745875
Ali Mehdi2:27â¯PM
42101-0883203-9
Taj Ahmed2:27â¯PM
42101-5086613-3
Siyam Ansari2:27â¯PM
45504-6691184-5
Asfa Tabish2:27â¯PM
42201-3317436-4
Gul Zaman Shaikh2:27â¯PM
42301-4208474-9
Gul Zaman
Rohan Wasim2:27â¯PM
4210156852483
Mahek Ali2:27â¯PM
4220119350184
Irtiqa Khan2:27â¯PM
42501-1882684-3
Hammad Khan2:27â¯PM
42201-2206678-9
mansoor ahmed2:27â¯PM
41303-1217008-9
imran jamil2:27â¯PM
42201-2367694-3
Junaid Khan2:27â¯PM
4250118835393
Saira Shaikh2:27â¯PM
4220182635186
Shariq Bashir2:27â¯PM
42101-1743803-7
Asmat Mehmood2:27â¯PM
423018695739
Raheel Nadeem2:27â¯PM
4220114028509
Saba Ali2:27â¯PM
42301-3905834-2
adeel Zaman2:27â¯PM
4240116015521 adeel zaman
Rosh Mirza2:27â¯PM
4420651403848
Ashar Khaliq2:27â¯PM
4200004676915
syed farman ali shah2:27â¯PM
1510203461495
Haroon Saleem2:27â¯PM
4240156992579
Shakeel Ahmed2:27â¯PM
4240119589433
Syed Usman Ghani2:27â¯PM
4210109155877
Abdul Samad Shaikh2:27â¯PM
4210255467543
Muhammad Saad2:27â¯PM
42201-4144981-5
Vishah Fatima2:27â¯PM
4210170628928
KAMRAN KHATRI2:27â¯PM
4230198076489
Shafaat Ahmed Khan2:27â¯PM
42201-3225780-3
Uzma Farogh2:27â¯PM
4210190028920
Akbar Khan2:27â¯PM
4220106865377
bilal2:28â¯PM
4210164911883
4210164911883
Bilal Khan2:28â¯PM
42501-3607843-1
Abdul Samad Shaikh2:28â¯PM
4210184328497
Xyz2:28â¯PM
4210118094301
Mahpara Badar2:28â¯PM
4210111752498
Hasan Mehdi2:28â¯PM
4210144676677
Imran Khan2:28â¯PM
4130498094753
Jahanzeb Siddiqui2:29â¯PM
4210169925379
Omema Akhtar2:29â¯PM
4210151840638 omema Akhtar
Raniya Khan2:29â¯PM
42201-9978093-2
aqsa akmal2:29â¯PM
4220145184200
Javeed Ahmed2:30â¯PM
4220141864935
Ashar Khaliq2:30â¯PM
%d
faranaz keshwani2:31â¯PM
42201-7992036-2
42201-7992036-2 Faranaz Surani
Ahmed Naseem2:32â¯PM
13 digit
Saba Ali2:32â¯PM
13
Talaal Yousoof2:32â¯PM
13
Danish Siddiquie2:32â¯PM
13
"""


import re
import pandas as pd

txt = data.replace("-","") #replace hyphen

#find 13 digits
cnic = re.findall('\d{13}',txt)#apply regex
cnic = list(set(cnic)) #set in list


print("count:",len(cnic))
df = pd.DataFrame({"CNIC":cnic})
df.to_excel("attendance.xlsx", index = False) #skip index column
df

count: 74

             CNIC
0   4220199780932
1   4220103150553
2   4420433352693
3   4210147179805
4   4210184328497
..            ...
69  4240116015521
70  4240119589433
71  4220158772002
72  4250150754028
73  4230139058342

[74 rows x 1 columns]

In [36]:
# extract name
data = """
Team NED Academy12:59â¯PM
Sir please start recording  pleas
Iqra Ismail1:01â¯PM
no
Muhammad Abubakar1:01â¯PM
sir class end pe assignment ke baray mei thora guide krdejye ga
Iqra Ismail1:02â¯PM
yes
Altaf Hussain Bakhwani1:04â¯PM
yes
Muhammad Abubakar1:04â¯PM
clear hai sir
Talaal Yousoof1:04â¯PM
yes
Altaf Hussain Bakhwani1:07â¯PM
yes, action = method, character = attribute
Talaal Yousoof1:09â¯PM
what was attribute pls?
Uzma Farogh1:09â¯PM
sir some students are trying to join. please let them in
faranaz keshwani1:12â¯PM
how do you record attendance on online classes
Asfa Tabish1:23â¯PM
sir method and attribute repeat krdain pls
Ahmed Naseem1:25â¯PM
Yes, main ne bhi late join kiya hai. It would be helpful if you can revise a bit.
Ashar Khaliq1:39â¯PM
print(name.lower().count("m"))
Rosh Mirza1:41â¯PM
name = "I love my country "
name = name.casefold()
print("y count:",name.count('y'),"m count :",name.count('m'))
You2:17â¯PM
24mrw4t
Imran Haider2:26â¯PM
3130315904511
Muhammad Abubakar2:26â¯PM
42201-1270634-5
Aamir Pingal2:26â¯PM
423012945634
Talaal Yousoof2:26â¯PM
4220158211299
Ahmed Naseem2:26â¯PM
4200066399757
Muhammad Ovais2:26â¯PM
42101-4941-769-5
Atif Salam2:26â¯PM
42201-9446591-3
Altaf Hussain Bakhwani2:26â¯PM
4220105815527
Feroz Gul2:26â¯PM
44204-3335269-3
Jawwad Khan2:26â¯PM
42201-9848624-7
Mahnoor Shoukat2:26â¯PM
4250150754028
hanfia sattar2:26â¯PM
4220151056096
Hiba Rafiq2:26â¯PM
4230185868058
Sadia Javed2:26â¯PM
4220158772002
Hafsa Imtiaz2:26â¯PM
42201-8903447-4
Fahad Hashmi2:27â¯PM
4210180636569
Iqra Ismail2:27â¯PM
4220113160602
Azeem Khan2:27â¯PM
42101-7583355-9
muhammad usman2:27â¯PM
33203-1390549-7
Owais Saeed2:27â¯PM
4210187416487
Dareer Khalid2:27â¯PM
4220103150553
Tauqir Ahmed2:27â¯PM
4220157915361
asad ahmad2:27â¯PM
3130349769793
FJ2:27â¯PM
4210174737043
Abdul Rehman2:27â¯PM
4210113955917
Danish Siddiquie2:27â¯PM
4230174890321
Huzaifa Aazmi2:27â¯PM
42101-4717980-5
Waqas Khan2:27â¯PM
35202-2018037-1
Memon Nadeemhabib2:27â¯PM
4130627627273
Habib Sufyan2:27â¯PM
42101-9546976-1
waqar saleem2:27â¯PM
3740611871985
Muhammad Umer Farooq2:27â¯PM
4250141745875
Ali Mehdi2:27â¯PM
42101-0883203-9
Taj Ahmed2:27â¯PM
42101-5086613-3
Siyam Ansari2:27â¯PM
45504-6691184-5
Asfa Tabish2:27â¯PM
42201-3317436-4
Gul Zaman Shaikh2:27â¯PM
42301-4208474-9
Gul Zaman
Rohan Wasim2:27â¯PM
4210156852483
Mahek Ali2:27â¯PM
4220119350184
Irtiqa Khan2:27â¯PM
42501-1882684-3
Hammad Khan2:27â¯PM
42201-2206678-9
mansoor ahmed2:27â¯PM
41303-1217008-9
imran jamil2:27â¯PM
42201-2367694-3
Junaid Khan2:27â¯PM
4250118835393
Saira Shaikh2:27â¯PM
4220182635186
Shariq Bashir2:27â¯PM
42101-1743803-7
Asmat Mehmood2:27â¯PM
423018695739
Raheel Nadeem2:27â¯PM
4220114028509
Saba Ali2:27â¯PM
42301-3905834-2
adeel Zaman2:27â¯PM
4240116015521 adeel zaman
Rosh Mirza2:27â¯PM
4420651403848
Ashar Khaliq2:27â¯PM
4200004676915
syed farman ali shah2:27â¯PM
1510203461495
Haroon Saleem2:27â¯PM
4240156992579
Shakeel Ahmed2:27â¯PM
4240119589433
Syed Usman Ghani2:27â¯PM
4210109155877
Abdul Samad Shaikh2:27â¯PM
4210255467543
Muhammad Saad2:27â¯PM
42201-4144981-5
Vishah Fatima2:27â¯PM
"""
import re
import pandas as pd

#pick format
#Rosh Mirza1:41â¯PM
#name = re.findall('Rosh Mirza1:41â¯PM')
#add () between required string 
#name = re.findall('(Rosh Mirza)1:41â¯PM')
#dot | steric - for all  |  \d : string | + : pick string full length
#names = re.findall('(.+)\d+:\d+â¯PM',data)
names = re.findall('(.*)\d+:\d+â¯PM',data)

['Team NED Academy1',
 'Iqra Ismail',
 'Muhammad Abubakar',
 'Iqra Ismail',
 'Altaf Hussain Bakhwani',
 'Muhammad Abubakar',
 'Talaal Yousoof',
 'Altaf Hussain Bakhwani',
 'Talaal Yousoof',
 'Uzma Farogh',
 'faranaz keshwani',
 'Asfa Tabish',
 'Ahmed Naseem',
 'Ashar Khaliq',
 'Rosh Mirza',
 'You',
 'Imran Haider',
 'Muhammad Abubakar',
 'Aamir Pingal',
 'Talaal Yousoof',
 'Ahmed Naseem',
 'Muhammad Ovais',
 'Atif Salam',
 'Altaf Hussain Bakhwani',
 'Feroz Gul',
 'Jawwad Khan',
 'Mahnoor Shoukat',
 'hanfia sattar',
 'Hiba Rafiq',
 'Sadia Javed',
 'Hafsa Imtiaz',
 'Fahad Hashmi',
 'Iqra Ismail',
 'Azeem Khan',
 'muhammad usman',
 'Owais Saeed',
 'Dareer Khalid',
 'Tauqir Ahmed',
 'asad ahmad',
 'FJ',
 'Abdul Rehman',
 'Danish Siddiquie',
 'Huzaifa Aazmi',
 'Waqas Khan',
 'Memon Nadeemhabib',
 'Habib Sufyan',
 'waqar saleem',
 'Muhammad Umer Farooq',
 'Ali Mehdi',
 'Taj Ahmed',
 'Siyam Ansari',
 'Asfa Tabish',
 'Gul Zaman Shaikh',
 'Rohan Wasim',
 'Mahek Ali',
 'Irtiqa Khan',
 'Hammad Khan',
 'mansoor ahmed',
 'imran jamil',
 'Junaid Khan',
 'Saira Shaikh',
 'Shariq Bashir',
 'Asmat Mehmood',
 'Raheel Nadeem',
 'Saba Ali',
 'adeel Zaman',
 'Rosh Mirza',
 'Ashar Khaliq',
 'syed farman ali shah',
 'Haroon Saleem',
 'Shakeel Ahmed',
 'Syed Usman Ghani',
 'Abdul Samad Shaikh',
 'Muhammad Saad',
 'Vishah Fatima']

In [66]:
data = """
12:05:40 From Ali Asar To Everyone : PIAIC-187258
12:05:41 From Hasnain Munir To Everyone : PIAIC-187272
12:05:44 From Shaheer Baig To Everyone : PIAIC-169519
12:05:45 From Humera Naz To Everyone : PIAIC-173431
12:05:47 From Sadia Anwar To Everyone : PIAIC-180028
12:05:47 From Muhammad Mehroz To Everyone : PIAIC-131496
12:05:47 From Home To Everyone : PIAIC-172998
12:05:47 From Muhammad Sadullah = PIAIC-178950 To Everyone : PIAIC-178950
12:05:48 From Muhammad Uzair-177637 To Everyone : PIAIC-177637
12:05:48 From Taqwa Khaliq To Everyone : PIAIC-173701 TAQWA KHALIQ
12:05:48 From asghar ibraheem CNC-012105 To Everyone : CNC-012105
12:05:49 From Faisal Bashir-177802 To Everyone : PIAIC-177802
12:05:50 From Talha Munir Rana To Everyone : PIAIC-173761
12:05:52 From Abdul Qadar To Everyone : PIAIC-172941
12:05:57 From Dr. Bhagwan Das To Everyone : PIAIC-96879
12:05:57 From Uzair Ullah (PIAIC169405) To Everyone : PIAIC-169405
12:06:00 From Arshad To Everyone : PIAIC168092
12:06:01 From PIAIC188523 Subhan Ahmed To Everyone : PIAIC188523
12:06:04 From Taqwa Khaliq To Everyone : PIAIC 173701
12:06:10 From Ali Asar To Everyone : PIAIC-188720
12:06:23 From Mohammad Javed To Everyone : WhatsApp number?
12:06:28 From Gulshan Ali To Everyone : PIAIC-176719
12:06:29 From M Ali Asif Khan - PIAIC-57947 To Everyone : PIAIC-57947
12:06:33 From Usman Noor PIAIC-188401 To Everyone : PIAIC-188401
12:06:46 From Zia (piaic121514) To Everyone : thanks
12:06:49 From Sohaib Baseer Ahmad To Everyone : PIAIC67260
12:40:20 From Ali Asar To Everyone : PIAIC-187258
"""
import re

#pick string
#12:06:33 From Usman Noor PIAIC-188401 To Everyone : PIAIC-188401
#txt = re.findall('12:06:33 From Usman Noor PIAIC-188401 To Everyone : PIAIC-188401',data)
#add () required feilds
#txt = re.findall('(\d{2}:\d{2}:\d{2}) From (.*) PIAIC-188401 To Everyone : (PIAIC-188401)',data)
txt = re.findall('(\d{2}:\d{2}:\d{2}) From (.*) To Everyone : (PIAIC-?\d{5,6})',data)
#txt

d = pd.DataFrame(txt,columns=["Time","Name","Roll No"])
d

        Time                              Name       Roll No
0   12:05:40                          Ali Asar  PIAIC-187258
1   12:05:41                     Hasnain Munir  PIAIC-187272
2   12:05:44                      Shaheer Baig  PIAIC-169519
3   12:05:45                        Humera Naz  PIAIC-173431
4   12:05:47                       Sadia Anwar  PIAIC-180028
5   12:05:47                   Muhammad Mehroz  PIAIC-131496
6   12:05:47                              Home  PIAIC-172998
7   12:05:47  Muhammad Sadullah = PIAIC-178950  PIAIC-178950
8   12:05:48             Muhammad Uzair-177637  PIAIC-177637
9   12:05:48                      Taqwa Khaliq  PIAIC-173701
10  12:05:49              Faisal Bashir-177802  PIAIC-177802
11  12:05:50                  Talha Munir Rana  PIAIC-173761
12  12:05:52                       Abdul Qadar  PIAIC-172941
13  12:05:57                   Dr. Bhagwan Das   PIAIC-96879
14  12:05:57         Uzair Ullah (PIAIC169405)  PIAIC-169405
15  12:06:00                            Arshad   PIAIC168092
16  12:06:01          PIAIC188523 Subhan Ahmed   PIAIC188523
17  12:06:10                          Ali Asar  PIAIC-188720
18  12:06:28                       Gulshan Ali  PIAIC-176719
19  12:06:29     M Ali Asif Khan - PIAIC-57947   PIAIC-57947
20  12:06:33           Usman Noor PIAIC-188401  PIAIC-188401
21  12:06:49               Sohaib Baseer Ahmad    PIAIC67260
22  12:40:20                          Ali Asar  PIAIC-187258